### ISSUE TITLE
OnchainAPI getgroupmembers issue

### ISSUE THREAD

**Issue by jdhyun09** [InterRep/interrep.js#5]
https://github.com/interep-project/interep.js/blob/5bc3350c1a05bf58bc25fcac5150ed887cf6c756/packages/api/src/onchainAPI.ts#L77

There seems to be a problem with creatproof. Perhaps there is a problem with merkleproof. This seems to be a problem caused by members not being sorted by index in the subgraph.

`members(where: { group: "${groupId}" }, orderBy: index) { `

If it is changed as follows, it will be good when using OnchainAPI's getGroupMembers. (Useful for leaveGroup, createProof)

Other features seem to be very useful. Thank you!

**Comment by cedoor** [comment]
Thanks @jdhyun09, it should work now!
